###
     stu
###
GET http://localhost/stu/del/{{id}}

###
GET http://localhost/stu/findAll

###
GET http://localhost/stu/{{id}}

###
POST http://localhost/stu/add

###
POST http://localhost/stu/update

###  {"stu_id":int,"pwd":""}
POST http://localhost/stu/updatePwd

###
###   tch
###
GET http://localhost/tch/findAll

###
GET http://localhost/tch/{{id}}

###
GET http://localhost/tch/del/{{id}}

###
POST http://localhost/tch/add

###
POST http://localhost/tch/update

###  {"tch_id":int,"pwd":""}
POST http://localhost/tch/updateTchPwd

###
     commq
###
GET http://localhost/commq/findAll

###
GET http://localhost/commq/{{id}}

###  {"text":""}
GET http://localhost/commq/findByText

###
GET http://localhost/commq/del/{{id}}

###
POST http://localhost/commq/add

###  {"id":"","text":""}
POST http://localhost/commq/updateText

###  {"id":"","answer":""}
POST http://localhost/commq/updateAnswer

###
POST http://localhost/commq/update

###
###  labq
###

###
GET http://localhost/labq/findAll

###
GET http://localhost/labq/{{id}}

###  {"text":""}
GET http://localhost/labq/findByText

###
GET http://localhost/labq/del/{{id}}

###
POST http://localhost/labq/add

###  {"id":"","text":""}
POST http://localhost/labq/updateText

###  {"id":"","answer":""}
POST http://localhost/labq/updateAnswer
